version: '3.9'

services:

  server_nginx_01:
    image: nginx:1.25.3-alpine
    container_name: server-nginx-01
    working_dir: /usr/share/nginx/html
    restart: always
    environment:
      - NGINX_PORT=80
      - TERM=xterm
    volumes:
      - ./www:/usr/share/nginx/html/www
      - ./conf.d/nginx.conf:/etc/nginx/nginx.conf
      - ./conf.d/localhost.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "81:80"
    networks:
      - server_nginx_network

networks:
  server_nginx_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.11.0.0/24
          gateway: 172.11.0.1
